format:
  html: 
    theme: zephyr

project:
  type: book

book:
  title: "Statisical Analysis, Visualization & Inference (SAVI) Workshops, with Python"
  author: "Ryan Her"
  sidebar:
    logo: "SAVIsticker.png"
  favicon: "SAVIsticker.png"
  chapters:
    - part: "Preface"
      chapters:
      - index.qmd
      - preface.qmd
    - part: "Workshops"
      chapters: 
      - WS_1.ipynb
      - WS_2.ipynb
      - WS_3.ipynb  
execute:
  echo: true

launch:
  colab: true